DIOS-6232: maxBitrate, forcePlayoutDelayMin & forcePlayoutDelayMax
dolbyio-samples/rts-app-ios-viewer pull request #201
Opened 2024-07-17 20:04 UTC by sheiladoherty-dolby

- Added maxBitrate to "More Stream Configurations" view on Landing 
- Passed through maxBitrate, forcePlayoutDelayMin & forcePlayoutDelayMax to the SDK for playback

![Simulator Screenshot - iPhone 15 - 2024-07-17 at 13 25 36](https://github.com/user-attachments/assets/021262ff-fb30-4889-b59d-5671041ebdb8)

![Simulator Screenshot - iPhone 15 - 2024-07-17 at 13 26 03](https://github.com/user-attachments/assets/225fc04b-2ba2-4bb1-961d-4b14e86aea89)

![Simulator Screenshot - iPhone 15 - 2024-07-17 at 13 26 18](https://github.com/user-attachments/assets/bf5d3241-c11d-4329-92ed-42956f8ab7a5)

2024-07-17 23:32 UTC, aravind-raveendran commented on LocalPackages/RTSCore/Sources/RTSCore/Models/SubscriptionConfiguration.swift
> +    {
Hi @sheiladoherty-dolby - what's the coding style that you follow ? 

I see some examples here:
https://github.com/kodecocodes/swift-style-guide?tab=readme-ov-file#function-declarations

2024-07-17 23:42 UTC, aravind-raveendran commented on LocalPackages/RTSCore/Sources/RTSCore/Manager/SubscriptionManager.swift
> +                clientOptions.maximumBitrate = NSNumber(value: configuration.maxBitrate)
@Yousif-CS @sheiladoherty-dolby - We have a mix of the numeric types that's used in this `MCClientOptions` type. NSNumber and Int. I think they can all be unsigned int's and bring some uniformity?

2024-07-17 23:46 UTC, aravind-raveendran commented on LocalPackages/RTSCore/Sources/RTSCore/Manager/SubscriptionManager.swift
> +                clientOptions.maximumBitrate = NSNumber(value: configuration.maxBitrate)
or we use NSNumber just as we want it to be null by default ?

2024-07-17 23:58 UTC, aravind-raveendran commented on interactive-player/Interactive Viewer/Managers/Persistence/RTSViewer.xcdatamodeld/RTSViewer.xcdatamodel/contents
> +        <attribute name="maxBitrate" optional="YES" attributeType="Integer 32" defaultValueString="0" usesScalarValueType="YES"/>
We can use `usesScalarValueType=NO` so that the value is stored and retrieved as an optional NSNumber in the persistence too ? So it aligns with what the SDK require it to be ?

2024-07-18 00:01 UTC, aravind-raveendran commented on interactive-player/Interactive Viewer/Managers/Persistence/StreamDataManager.swift
> +                                                                             cacheName: nil)
Lets follow one of this to intend function calls?
https://github.com/kodecocodes/swift-style-guide?tab=readme-ov-file#function-calls
https://google.github.io/swift/#function-calls

2024-07-18 00:04 UTC, aravind-raveendran commented on interactive-player/Interactive Viewer/Managers/VideoTracksManager.swift
> +            self.videoQualitySubject.send(sourceToVideoQuality)
Lets no use explicit self in cases where except in scenarios where we want to disambiguate, like in an assignment?

https://google.github.io/swift/#initializers

2024-07-18 00:12 UTC, aravind-raveendran commented on interactive-player/Interactive Viewer/Managers/VideoTracksManager.swift
> +                  await self.layerEventsObservationDictionary[source.sourceId] == nil else { return }
Let's follow one of these for indentation?  https://github.com/kodecocodes/swift-style-guide?tab=readme-ov-file#control-flow or https://google.github.io/swift/#control-flow-statements ? 

If it's too long for one line, like below from the kodeco swift styling guide is better ?

```
guard 
  let number1 = number1,
  let number2 = number2,
  let number3 = number3 
else {
  fatalError("impossible")
}
```

2024-07-18 00:13 UTC, aravind-raveendran commented on interactive-player/Interactive Viewer/Managers/VideoTracksManager.swift
> +        self.sourceToTasks.removeAll()
Explicit use of `self.` here ?

2024-07-18 00:14 UTC, aravind-raveendran commented on interactive-player/Interactive Viewer/Views/RecentStreams/RecentStreamsViewModel.swift
> +import RTSCore
👍

2024-07-18 00:15 UTC, aravind-raveendran commented on interactive-player/Interactive Viewer/Views/StreamDetailInputScreen/StreamDetailInputScreen.swift
> +    @State private var maxPlayoutDelay: = Float(SubscriptionConfiguration.Constants.jitterMinimumDelayMs)
This line is a compilation error ?

2024-07-18 00:20 UTC, aravind-raveendran commented on interactive-player/Interactive Viewer/Views/StreamDetailInputScreen/StreamDetailInputScreen.swift
> +    @State private var setMaxBitrate: Bool = false
Reading the property `setMaxBitrate ` in isolation gives me an impression it's a setter ? May be use `showMaxBitrate` or `isShowingMaxBitRate` or something similar to give an impression its a bool ?

2024-07-18 00:21 UTC, aravind-raveendran commented on interactive-player/Interactive Viewer/Views/StreamDetailInputScreen/StreamDetailInputScreen.swift
> +    @State private var maxBitrateString: String = "0"
May be just use on State variable `maxBitrateString` and read the int value out of it when needed, thus one source of truth ?

2024-07-18 00:23 UTC, aravind-raveendran commented on interactive-player/RTSViewer.xcodeproj/project.pbxproj
> +				CODE_SIGN_IDENTITY = "Apple Development";
Lets not set any code signing identity in the project, its set via xcconfig files in this project. A good chance this change will break the CI ?

2024-07-18 00:25 UTC, aravind-raveendran commented on rts-viewer-ios/RTSViewer.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +        "version" : "1.8.5"
Let's remove changes to this file as this project is no more maintained and an update may need more testing and code changes ?

2024-07-18 00:28 UTC, aravind-raveendran requested changes
Hi @sheiladoherty-dolby - let's have a chat on the coding style changes that were incorporated into this PR. I used Kodeco/former Raywenderlich styles in this project. Happy to see your thoughts and the style guide you follow. Its best to not mix and match though ?

2024-07-18 15:52 UTC, sheiladoherty-dolby commented
> Hi @sheiladoherty-dolby - let's have a chat on the coding style changes that were incorporated into this PR. I used Kodeco/former Raywenderlich styles in this project. Happy to see your thoughts and the style guide you follow. Its best to not mix and match though ?

We have always used SwiftFormat for our code formatting in the Denver office. It has pretty standard code practices that it formats code to & any code I touch will get formatted to these standards. But if you would prefer a different method of formatting for this codebase, I can try to refrain from formatting my code with it when I am working on this codebase.

2024-07-18 15:56 UTC, sheiladoherty-dolby commented on interactive-player/Interactive Viewer/Managers/VideoTracksManager.swift
> +                  await self.layerEventsObservationDictionary[source.sourceId] == nil else { return }
I think that is just a personal preference. This is how I would typically format that:
```suggestion
                  guard  let number1 = number1,
                  let number2 = number2,
                   let number3 = number3  else {
                           fatalError("impossible")
                   }
```

2024-07-18 15:57 UTC, sheiladoherty-dolby commented on LocalPackages/RTSCore/Sources/RTSCore/Models/SubscriptionConfiguration.swift
> +    {
SwiftFormat

2024-07-18 17:20 UTC, sheiladoherty-dolby commented on LocalPackages/RTSCore/Sources/RTSCore/Manager/SubscriptionManager.swift
> +                clientOptions.maximumBitrate = NSNumber(value: configuration.maxBitrate)
Either one if fine with me, but that is of course a change that needs to be made on the SDK

2024-07-18 17:47 UTC, sheiladoherty-dolby commented on LocalPackages/RTSCore/Sources/RTSCore/Models/SubscriptionConfiguration.swift
> +    {
The formatting I showed is the style we have adopted here in Denver & is an acceptable coding practice. But it doesn't really matter to me either way.

2024-07-18 22:38 UTC, aravind-raveendran commented on LocalPackages/RTSCore/Sources/RTSCore/Models/SubscriptionConfiguration.swift
> +    {
Not sure if we need a formatter added, we use SwiftLint in the project but that handles for indentation, line spacing, function lengths etc as opposed to code formatting. 
May be it's good to follow a style guide instead for formatting tool here, their formatting seems a bit different when compared to style guides followed in Apple framework itself ? Especially line 42 to have opening brace in a separate line is more seen in objc where as swift keeps the opening braces  `{` to the same line as that of the function itself ?

2024-07-18 22:44 UTC, sheiladoherty-dolby commented on LocalPackages/RTSCore/Sources/RTSCore/Models/SubscriptionConfiguration.swift
> +    {
I don't add SwiftFormat to my projects, I just have it running through Xcode. It formats a file with a key code. But like I said, I don't think it's something we really need to worry about. Our code is pretty tidy & I feel like we are quibbling over spaces.

2024-07-18 22:53 UTC, aravind-raveendran commented on LocalPackages/RTSCore/Sources/RTSCore/Models/SubscriptionConfiguration.swift
> +    {
My question was more on the code styling/formatting changes that you all through in this PR.

2024-07-18 22:55 UTC, aravind-raveendran commented on LocalPackages/RTSCore/Sources/RTSCore/Models/SubscriptionConfiguration.swift
> +    {
From what I understand from your comments, it was introduced by swiftformat which is not a tool rest of the team uses.

2024-07-18 22:57 UTC, aravind-raveendran commented on rts-viewer-ios/RTSViewer.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +        "version" : "1.8.5"
Please leave a reason when you marked a conversation as resolved, so the actual comment author understands it too ?

2024-07-18 23:03 UTC, aravind-raveendran commented on rts-viewer-ios/RTSViewer.xcodeproj/project.pbxproj
> +				CODE_SIGN_STYLE = Manual;
Like I said in the above project file too, these inline code signing changes are not needed as this project sets code signing via xcconfig files

2024-07-18 23:43 UTC, aravind-raveendran commented on interactive-player/Interactive Viewer/Views/StreamDetailInputScreen/StreamDetailInputScreen.swift
> +            maxPlayoutDelay: playoutDelayMax,
The rest of the debug options in this screen is only applied to the stream details inputted by the user, these three options should also be the same ?

2024-07-18 23:45 UTC, aravind-raveendran commented on LocalPackages/RTSCore/Sources/RTSCore/Manager/SubscriptionManager.swift
> +                clientOptions.maximumBitrate = NSNumber(value: configuration.maxBitrate)
NSNumber is used to ensure nullability so no update needed for this one I assume

2024-07-18 23:52 UTC, sheiladoherty-dolby commented on interactive-player/Interactive Viewer/Views/StreamDetailInputScreen/StreamDetailInputScreen.swift
> +            maxPlayoutDelay: playoutDelayMax,
If you look at line 418 & 419, it will only show values if there have been values add by the use, otherwise it will be `nil`.
```suggestion
        let playoutDelayMin = showPlayoutDelay ? UInt(minPlayoutDelay) : nil
        let playoutDelayMax = showPlayoutDelay ? UInt(maxPlayoutDelay) : nil
```

2024-07-18 23:54 UTC, aravind-raveendran commented on interactive-player/RTSViewer.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> -  ],
I feel it's a good practice to checkin this file as the builds in CI and every other developer uses the same SDK version. So what's tested in developer machines is what gets build and deployed to the stores or for testing. 
What's your thoughts?

2024-07-18 23:58 UTC, aravind-raveendran commented on rts-viewer-ios/RTSViewer.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +  "version" : 3
From my learnings in the past, this version updates happens when we use different Xcode version to build our project. Checking in this change might cause failures in the build pipeline as the CI is locked to use `Xcode_15.2`, see `.env.default` in the folder fastlane. Also GitHub actions are a normally bit behind in updating their runners with the most up to date Xcode releases

2024-07-19 00:08 UTC, aravind-raveendran commented on interactive-player/Interactive Viewer/Views/StreamDetailInputScreen/StreamDetailInputScreen.swift
> +            maxPlayoutDelay: playoutDelayMax,
Yes I understand and it's a good thing in my opinion too. 

However the demo stream doesn't currently use the other debug options changed by the user, for example - url, jitter buffer, disable audio etc. These values are all set to use the defaults.

So my thought is - for the demo stream we should align all debug options to either use the `defaults(which is how it is now)` or the `values that the user input (which is what you are doing for these three options)` 

cc @RameshDPrasad can take a call on this one ?

2024-07-19 01:21 UTC, RameshDPrasad commented on interactive-player/Interactive Viewer/Views/StreamDetailInputScreen/StreamDetailInputScreen.swift
> +            maxPlayoutDelay: playoutDelayMax,
Passing nil is ok in that case SDK will not send anything to server and server will use its own default.
Can you confirm this @Yousif-CS

2024-07-19 01:31 UTC, RameshDPrasad commented on interactive-player/Interactive Viewer/Views/StreamDetailInputScreen/StreamDetailInputScreen.swift
> +            maxPlayoutDelay: playoutDelayMax,
I misunderstood the discussion here. For demo stream do not apply any debug config

2024-07-19 01:35 UTC, aravind-raveendran commented on interactive-player/RTSViewer.xcodeproj/project.pbxproj
> +				CODE_SIGN_IDENTITY = "";
This change on the project setting is not harmful but still not needed for code signing?

2024-07-19 03:09 UTC, aravind-raveendran commented on interactive-player/Interactive Viewer/Managers/VideoTracksManager.swift
> +                  await self.layerEventsObservationDictionary[source.sourceId] == nil else { return }
What I am proposing is let's follow a standard industry guideline. https://google.github.io/swift/#control-flow-statements or https://github.com/kodecocodes/swift-style-guide?tab=readme-ov-file#control-flow which are more or less the same and most accepted guideline among swift developers.

For example, the formatting changes applied file is completely unrelated to the scope of JIRA you are working on. When you are introducing new style/formatting practices and applying it to unrelated files. Examples I am referring to are `self.` to access all properties and fixing indentation to something others are not familiar with needs a broader discussion in the team and agreement.

2024-07-19 03:24 UTC, RameshDPrasad commented on interactive-player/Interactive Viewer/Managers/VideoTracksManager.swift
> +                  await self.layerEventsObservationDictionary[source.sourceId] == nil else { return }
@sheiladoherty-dolby let's stick to the conventions which was already being followed in this repo, the team here is familiar with it and follows it as well. We can have a discussion about it in our next meeting for improvements.

2024-07-19 16:11 UTC, sheiladoherty-dolby commented on rts-viewer-ios/RTSViewer.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +  "version" : 3
Yes, we are on 15.4 in our office

2024-07-19 16:16 UTC, sheiladoherty-dolby commented on interactive-player/RTSViewer.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> -  ],
We are using 15.4 in Denver.

2024-07-22 00:24 UTC, aravind-raveendran approved these changes
Good work and LGTM !!

2024-07-22 16:09 UTC, merged